"""Tests for the Plane catch-all proxy route in plane_proxy.py.

Mirrors tests/test_taiga_proxy.py's SSRF/passthrough coverage for the
equivalent Plane surface. Plane has no /auth exchange endpoint (token is
generated by the user in Plane's own UI, not obtained by proxying a
password login), so there's no equivalent of Taiga's TestProxyTaigaAuth.
"""

import json
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from fastapi.testclient import TestClient

from backend.app.main import app


@pytest.fixture
def client():
    return TestClient(app)


def _mock_upstream(status_code: int, body: dict | list, content_type: str = "application/json"):
    resp = MagicMock()
    resp.content = json.dumps(body).encode()
    resp.status_code = status_code
    resp.headers = {"content-type": content_type}
    resp.json.return_value = body
    return resp


def _patch_client(response):
    mock_http = MagicMock()
    mock_http.request = AsyncMock(return_value=response)
    return patch("backend.app.api.plane_proxy._get_client", return_value=mock_http), mock_http


class TestProxyPlaneCatchAll:
    PLANE_URL = "https://plane.example.test"
    API_KEY = "plane_pat_mykey"

    def test_get_forwarded_with_query_string(self, client):
        upstream = _mock_upstream(200, {"results": [{"id": "abc"}]})
        patcher, mock_http = _patch_client(upstream)
        with patcher:
            resp = client.get(
                "/api/pm/plane/workspaces/my-team/projects/p1/work-items/?per_page=50",
                headers={"X-Api-Key": self.API_KEY, "X-Plane-Url": self.PLANE_URL},
            )
        assert resp.status_code == 200
        call_args = mock_http.request.call_args
        assert call_args.kwargs["method"] == "GET"
        assert "work-items" in call_args.kwargs["url"]
        assert "per_page=50" in call_args.kwargs["url"]
        assert call_args.kwargs["headers"]["X-Api-Key"] == self.API_KEY
        assert "Authorization" not in call_args.kwargs["headers"]

    def test_post_body_forwarded(self, client):
        upstream = _mock_upstream(201, {"id": "abc", "name": "Work item"})
        patcher, mock_http = _patch_client(upstream)
        with patcher:
            resp = client.post(
                "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
                headers={"X-Api-Key": self.API_KEY, "X-Plane-Url": self.PLANE_URL},
                json={"name": "Work item"},
            )
        assert resp.status_code == 201
        call_args = mock_http.request.call_args
        assert call_args.kwargs["method"] == "POST"
        assert json.loads(call_args.kwargs["content"]) == {"name": "Work item"}

    def test_upstream_4xx_forwarded_as_is(self, client):
        upstream = _mock_upstream(404, {"detail": "Not found"})
        patcher, mock_http = _patch_client(upstream)
        with patcher:
            resp = client.get(
                "/api/pm/plane/workspaces/my-team/projects/p1/work-items/xyz/",
                headers={"X-Api-Key": self.API_KEY, "X-Plane-Url": self.PLANE_URL},
            )
        assert resp.status_code == 404
        assert resp.json()["detail"] == "Not found"

    def test_upstream_rate_limit_message_readable(self, client):
        upstream = _mock_upstream(429, {})
        patcher, mock_http = _patch_client(upstream)
        with patcher:
            resp = client.get(
                "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
                headers={"X-Api-Key": self.API_KEY, "X-Plane-Url": self.PLANE_URL},
            )
        assert resp.status_code == 429
        assert "60 requests/minute" in resp.json()["detail"]

    def test_missing_api_key_returns_401(self, client):
        resp = client.get(
            "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
            headers={"X-Plane-Url": self.PLANE_URL},
        )
        assert resp.status_code == 401

    def test_header_injection_blocked(self, client):
        resp = client.get(
            "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
            headers={"X-Api-Key": "key\r\nX-Evil: injected", "X-Plane-Url": self.PLANE_URL},
        )
        assert resp.status_code == 401

    def test_oversized_api_key_blocked(self, client):
        resp = client.get(
            "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
            headers={"X-Api-Key": "a" * 2001, "X-Plane-Url": self.PLANE_URL},
        )
        assert resp.status_code == 400

    def test_http_url_blocked(self, client):
        resp = client.get(
            "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
            headers={"X-Api-Key": self.API_KEY, "X-Plane-Url": "http://plane.example.test"},
        )
        assert resp.status_code == 400

    def test_ssrf_private_ip_blocked(self, client):
        resp = client.get(
            "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
            headers={"X-Api-Key": self.API_KEY, "X-Plane-Url": "https://192.168.1.1"},
        )
        assert resp.status_code == 400

    def test_ssrf_link_local_blocked(self, client):
        resp = client.get(
            "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
            headers={"X-Api-Key": self.API_KEY, "X-Plane-Url": "https://169.254.169.254"},
        )
        assert resp.status_code == 400

    def test_ssrf_localhost_blocked(self, client):
        resp = client.get(
            "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
            headers={"X-Api-Key": self.API_KEY, "X-Plane-Url": "https://localhost"},
        )
        assert resp.status_code == 400

    def test_missing_x_plane_url_with_no_config_returns_400(self, client):
        with patch("src.context_manager.load_config", return_value={"pm_tool": "taiga"}):
            resp = client.get(
                "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
                headers={"X-Api-Key": self.API_KEY},
            )
        assert resp.status_code == 400

    def test_config_fallback_used_when_no_header(self, client, monkeypatch):
        monkeypatch.setattr(
            "backend.app.api.ssrf.socket.getaddrinfo",
            lambda host, *a, **k: [(2, 1, 6, "", ("203.0.113.10", 0))],
        )
        upstream = _mock_upstream(200, {"results": []})
        patcher, mock_http = _patch_client(upstream)
        config = {"pm_tool": "plane", "plane_url": self.PLANE_URL}
        with patcher, patch("src.context_manager.load_config", return_value=config):
            resp = client.get(
                "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
                headers={"X-Api-Key": self.API_KEY},
            )
        assert resp.status_code == 200
        kw = mock_http.request.call_args.kwargs
        assert kw["headers"]["Host"] == "plane.example.test"
        assert "/api/v1/" in kw["url"]
        assert "203.0.113.10" in kw["url"]

    def test_default_plane_cloud_used_when_config_has_no_url(self, client, monkeypatch):
        monkeypatch.setattr(
            "backend.app.api.ssrf.socket.getaddrinfo",
            lambda host, *a, **k: [(2, 1, 6, "", ("203.0.113.10", 0))],
        )
        upstream = _mock_upstream(200, {"results": []})
        patcher, mock_http = _patch_client(upstream)
        config = {"pm_tool": "plane"}
        with patcher, patch("src.context_manager.load_config", return_value=config):
            resp = client.get(
                "/api/pm/plane/workspaces/my-team/projects/p1/work-items/",
                headers={"X-Api-Key": self.API_KEY},
            )
        assert resp.status_code == 200
        kw = mock_http.request.call_args.kwargs
        assert kw["headers"]["Host"] == "api.plane.so"
