"""Figma OAuth 2.0 — operator-gated, optional.

Apex's Figma integration normally uses a personal access token (PAT) the user
pastes in the browser. When the *deployment* registers a Figma OAuth app and sets
``FIGMA_OAUTH_CLIENT_ID`` / ``FIGMA_OAUTH_CLIENT_SECRET`` /
``FIGMA_OAUTH_REDIRECT_URI``, users can instead click "Connect with Figma".

Storage posture mirrors the PAT: the backend only performs the authorization-code
exchange (it holds the client secret); the resulting access token is handed back
to the browser and lives in sessionStorage — cleared on tab close, never persisted
server-side. Downstream the proxy treats the OAuth token as an opaque value and
forwards it as ``Authorization: Bearer`` (it lacks the ``figd_`` PAT prefix).

CSRF: the ``state`` value is generated by the browser, stored there, and verified
against the value Figma echoes back to the redirect URI — so the backend stays
stateless (consistent with the no-server-storage posture).

These routes MUST be registered before the figma_proxy catch-all (``/{path:path}``)
or the proxy swallows ``oauth/*`` and rejects it for a missing token.
"""

from __future__ import annotations

import base64
import logging
import os
from urllib.parse import urlencode

import httpx
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from backend.app.api.ssrf import egress_host_allowed, is_blocked_host, pinned_target

router = APIRouter()
_logger = logging.getLogger("apex.figma_oauth")

_AUTHORIZE_BASE = "https://www.figma.com/oauth"
# Figma's current token endpoint lives on api.figma.com (already SSRF-pinned and
# egress-allowed for the proxy). Client credentials go in the Basic auth header,
# grant params in the form body. If a deployment's app expects body credentials
# (the legacy www.figma.com/api/oauth/token style), move client_id/secret here.
_TOKEN_URL = "https://api.figma.com/v1/oauth/token"
_TOKEN_HOST = "api.figma.com"
_DEFAULT_SCOPES = "file_content:read,file_comments:read,projects:read"
_TIMEOUT = 15.0


def _config() -> dict | None:
    """The OAuth app config, or None when the deployment hasn't set it up."""
    cid = os.getenv("FIGMA_OAUTH_CLIENT_ID", "").strip()
    secret = os.getenv("FIGMA_OAUTH_CLIENT_SECRET", "").strip()
    redirect = os.getenv("FIGMA_OAUTH_REDIRECT_URI", "").strip()
    if not (cid and secret and redirect):
        return None
    scopes = os.getenv("FIGMA_OAUTH_SCOPES", "").strip() or _DEFAULT_SCOPES
    return {"client_id": cid, "client_secret": secret, "redirect_uri": redirect, "scopes": scopes}


class AuthorizeUrlResponse(BaseModel):
    url: str


class TokenRequest(BaseModel):
    code: str = Field(..., max_length=2_000)


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str = ""
    expires_in: int = 0


@router.get("/config")
def oauth_config() -> dict:
    """Whether the deployment offers the 'Connect with Figma' button."""
    return {"enabled": _config() is not None}


@router.get("/authorize-url", response_model=AuthorizeUrlResponse)
def authorize_url(state: str) -> AuthorizeUrlResponse:
    """Build the Figma authorization URL the browser redirects to."""
    cfg = _config()
    if cfg is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Figma OAuth is not configured.")
    state = (state or "").strip()
    if not state or len(state) > 256:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="A state value is required.")
    params = {
        "client_id": cfg["client_id"],
        "redirect_uri": cfg["redirect_uri"],
        "scope": cfg["scopes"],
        "state": state,
        "response_type": "code",
    }
    return AuthorizeUrlResponse(url=f"{_AUTHORIZE_BASE}?{urlencode(params)}")


@router.post("/token", response_model=TokenResponse)
def exchange_token(payload: TokenRequest) -> TokenResponse:
    """Exchange an authorization code for an access token (server-side, holds secret)."""
    cfg = _config()
    if cfg is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Figma OAuth is not configured.")
    code = payload.code.strip()
    if not code:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="An authorization code is required.")
    if is_blocked_host(_TOKEN_HOST) or not egress_host_allowed(_TOKEN_HOST):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Figma token host is blocked or not in the egress allowlist.",
        )

    basic = base64.b64encode(f"{cfg['client_id']}:{cfg['client_secret']}".encode()).decode()
    headers = {
        "Authorization": f"Basic {basic}",
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "application/json",
    }
    form = {"redirect_uri": cfg["redirect_uri"], "code": code, "grant_type": "authorization_code"}
    try:
        url, headers, ext = pinned_target(_TOKEN_URL, headers)
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Figma token host resolves to a private/blocked address.",
        ) from exc
    try:
        with httpx.Client(follow_redirects=False, timeout=_TIMEOUT) as client:
            resp = client.request(
                "POST", url, data=form, headers=headers, **({"extensions": ext} if ext else {})
            )
    except httpx.RequestError as exc:
        _logger.error("Figma token exchange failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Failed to reach Figma for token exchange.",
        ) from exc
    if resp.status_code >= 400:
        _logger.warning("Figma token exchange rejected: status=%s", resp.status_code)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Figma rejected the authorization code.",
        )
    try:
        data = resp.json()
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Figma returned a malformed token response.",
        ) from exc
    access = (data.get("access_token") or "").strip()
    if not access:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Figma returned no access token.",
        )
    return TokenResponse(
        access_token=access,
        refresh_token=(data.get("refresh_token") or ""),
        expires_in=int(data.get("expires_in") or 0),
    )
