"""Reverse proxy for all Plane.so API calls.

Mirrors taiga_proxy.py's shape: Plane instances (self-hosted or Cloud) are a
user-influenced host, so every request validates the URL server-side before
dialing out (SSRF guard), and credentials never leave the browser toward
Plane directly. Unlike Taiga, Plane's auth is a single Personal Access Token
(`X-API-Key` header) generated by the user in Plane's own UI — there is no
username/password exchange endpoint to proxy, so this module is just the
generic catch-all passthrough plus the SSRF validator.

Plane's workspace slug is not a separate anchor concern here: it's just a
path segment the caller includes (e.g. `workspaces/{slug}/projects/{id}/...`),
forwarded like any other path. deps.py is where the slug becomes a real
anchor concern, for Apex's own credential/instance-scoping identity check.
"""

import logging
from urllib.parse import urlparse

import httpx
from fastapi import APIRouter, Header, HTTPException, Request, Response, status
from fastapi.responses import JSONResponse

from backend.app.api.pm_http import ResponseTooLarge, check_response_size, send_with_retry
from backend.app.api.ssrf import egress_host_allowed, is_blocked_host, pinned_target

router = APIRouter()
_logger = logging.getLogger("apex.plane_proxy")

_TIMEOUT = 20.0
_CONNECT_TIMEOUT = 8.0
_KEEPALIVE_EXPIRY = 15.0
_client: httpx.AsyncClient | None = None

_DEFAULT_PLANE_URL = "https://api.plane.so"
_MAX_API_KEY_LEN = 2_000


def _get_client() -> httpx.AsyncClient:
    global _client
    if _client is None or _client.is_closed:
        _client = httpx.AsyncClient(
            follow_redirects=False,
            timeout=httpx.Timeout(_TIMEOUT, connect=_CONNECT_TIMEOUT),
            limits=httpx.Limits(keepalive_expiry=_KEEPALIVE_EXPIRY),
        )
    return _client


async def _reset_client() -> None:
    global _client
    old, _client = _client, None
    if old is not None and not old.is_closed:
        try:
            await old.aclose()
        except Exception:  # noqa: BLE001 — best-effort cleanup of a dead pool
            pass


async def _send(method: str, url: str, **kwargs) -> httpx.Response:
    return await send_with_retry(_get_client, _reset_client, method, url, logger=_logger, **kwargs)


def _pin(url: str, headers: dict) -> tuple[str, dict, dict]:
    """Pin the outbound target to a validated IP (DNS-rebinding guard).

    No relay path exists for Plane (that's a Taiga-Cloud/Azure-firewall
    specific workaround) — every Plane request pins directly.
    """
    try:
        return pinned_target(url, headers)
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Plane host resolves to a private/blocked address.",
        ) from exc


def _validate_plane_url(url: str, *, source: str = "X-Plane-Url") -> str:
    """Require https:// and a non-private hostname to prevent SSRF.

    Applied to BOTH the X-Plane-Url header override and the workspace-config
    URL — mirrors taiga_proxy._validate_taiga_url exactly (see that function's
    docstring for why both paths need it: config is just as user-influenced
    as the header, being writable through the API).
    """
    url = url.strip().rstrip("/")
    if not url.startswith("https://"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"{source}: Plane instance URL must use https://.",
        )
    host = urlparse(url).hostname or ""
    if not host or is_blocked_host(host):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"{source} must not point to a private/loopback address.",
        )
    if not egress_host_allowed(host):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"{source}: host {host!r} is not in the egress allowlist.",
        )
    from src import context_manager

    from backend.app.api.ssrf import host_in_allowlist
    instance_allow = context_manager.get_instance_egress_allowlist(context_manager.instance_key(url))
    if not host_in_allowlist(host, instance_allow):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"{source}: host {host!r} is not in this instance's egress allowlist.",
        )
    return url


def _upstream_detail(resp: httpx.Response) -> str:
    """Best readable message out of a Plane error body.

    Plane's DRF-style errors use `detail` most commonly, sometimes a bare
    field-name-keyed dict of message lists — normalise to a single string,
    mirroring taiga_proxy._upstream_detail. Confirmed live against a real
    workspace: the paid-tier gate (e.g. Epics on a free plan) answers
    402 with `{"error": "Payment required", "error_code": 1999}` — a flat
    `error` key, not `detail` — hence the explicit check below.
    """
    try:
        data = resp.json()
    except ValueError:
        data = None
    if isinstance(data, dict):
        detail = data.get("detail")
        if isinstance(detail, str) and detail.strip():
            return detail.strip()
        error = data.get("error")
        if isinstance(error, str) and error.strip():
            return error.strip()
        # DRF validation-error shape: {"field": ["message", ...], ...}
        messages = [
            str(v) for values in data.values()
            if isinstance(values, list) for v in values
        ]
        if messages:
            return "; ".join(messages)
    elif isinstance(data, str) and data.strip():
        return data.strip()
    if resp.status_code == 401:
        return "Plane rejected the API key. Sign in again."
    if resp.status_code == 402:
        return "Plane rejected this request — the feature isn't available on this workspace's plan."
    if resp.status_code == 403:
        return "Plane denied access to this resource."
    if resp.status_code == 404:
        return "Plane could not find that resource."
    if resp.status_code == 429:
        return "Plane rate-limited this API key (60 requests/minute). Try again shortly."
    return f"Plane returned {resp.status_code}."


def _with_api_v1(base: str) -> str:
    """Append /api/v1 if not already present. Shared by both the header-override
    and config-fallback paths in _get_plane_url so a caller only ever needs to
    send the bare instance URL (https://api.plane.so, or a self-hosted domain)
    and Apex path segments (workspaces/{slug}/projects/{id}/...) with no /api/v1
    of their own — this normalisation is the only place that contract holds.

    Bug this fixes: earlier, only the config-fallback branch appended /api/v1;
    the (far more common, since it's the only path callers actually use so
    far) header-override branch silently built a URL missing /api/v1 entirely,
    which sent every request to the wrong path and got a real 404 back from
    Plane instead of the intended resource. Caught by a live manual test
    against api.plane.so — no unit test asserted the full target URL for the
    header-override branch, only for the config-fallback one.
    """
    base = base.rstrip("/")
    return base if base.endswith("/api/v1") else f"{base}/api/v1"


def _get_plane_url(x_plane_url: str = "") -> str:
    """Resolve Plane API base URL from header override or workspace config."""
    if x_plane_url:
        return _validate_plane_url(_with_api_v1(x_plane_url))
    from src import context_manager

    config = context_manager.load_config()
    if config.get("pm_tool") != "plane":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Workspace is not configured for Plane.",
        )
    plane_url = config.get("plane_url", "").rstrip("/") or _DEFAULT_PLANE_URL
    return _validate_plane_url(_with_api_v1(plane_url), source="Configured Plane URL")


@router.api_route("/{path:path}", methods=["GET", "POST", "PATCH", "DELETE"])
async def proxy_plane(
    path: str,
    request: Request,
    x_api_key: str = Header(default="", alias="X-Api-Key"),
    x_plane_url: str = Header(default="", alias="X-Plane-Url"),
) -> Response:
    """Forward any Plane REST API call server-side to eliminate browser CORS
    issues and keep the API key out of a direct browser->Plane connection."""
    if not x_api_key or "\r" in x_api_key or "\n" in x_api_key:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="X-Api-Key header required.",
        )
    if len(x_api_key) > _MAX_API_KEY_LEN:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid API key.",
        )
    base_url = _get_plane_url(x_plane_url)
    target_url = f"{base_url}/{path}"
    if request.url.query:
        target_url = f"{target_url}?{request.url.query}"

    body = b"" if request.method in ("GET", "HEAD") else await request.body()
    url, headers, ext = _pin(
        target_url,
        {
            "X-Api-Key": x_api_key,
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
    )

    try:
        resp = await _send(
            request.method,
            url,
            headers=headers,
            content=body or None,
            **({"extensions": ext} if ext else {}),
        )
        check_response_size(resp, logger=_logger, url=target_url)
    except httpx.RequestError as exc:
        _logger.error("Plane proxy failed to reach %s: %s", target_url, exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Failed to reach Plane instance.",
        ) from exc
    except ResponseTooLarge as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Plane instance returned a response that was too large.",
        ) from exc

    if resp.status_code >= 400:
        _logger.warning("plane_upstream_error status=%d path=%s", resp.status_code, path)
        return JSONResponse(
            {"detail": _upstream_detail(resp)},
            status_code=resp.status_code,
        )

    return Response(
        content=resp.content,
        status_code=resp.status_code,
        media_type=resp.headers.get("content-type", "application/json"),
    )
