export const AI_GROUNDING = {
  phase1SuggestEpics: ["project-concept.md", "guide-the-ai note"],
  phase1GapAnalysis: ["project-concept.md", "PM epics/stories"],
  phase1Constraints: ["project-concept.md", "tech-stack.md", "selected story scope"],
  phase1GenerateStories: ["project-concept.md", "figma-context.md", "guide-the-ai note"],
  phase1ReviewDraft: ["story draft", "clarifications"],
  phase1FigmaStories: ["figma-context.md", "selected Figma frames"],
  phase2TechStack: ["project-concept.md", "functional-spec.md", "guide-the-ai note"],
  phase2Design: ["project-concept.md", "functional-spec.md", "tech-stack.md", "figma-context.md", "guide-the-ai note"],
  phase2DesignDelta: ["functional-spec.md", "technical-spec.md", "design-bundle.md", "new story set"],
  phase2VisualSystem: ["ux-brief.md", "figma-context.md", "guide-the-ai note"],
  phase3Tasks: ["functional-spec.md", "technical-spec.md", "runtime-spec.md", "constraints.md", "github-context.md", "figma-context.md"],
  phase3Packs: ["functional-spec.md", "technical-spec.md", "runtime-spec.md", "constraints.md", "github-context.md", "developer tasks"],
  phase4TestPlan: ["functional-spec.md", "technical-spec.md", "developer packs", "github-context.md"],
  phase4EdgeCases: ["functional-spec.md", "technical-spec.md", "test-plan.md"],
  phase4FixBolt: ["failed scenarios", "QA notes", "test-plan.md", "developer packs"],
  phase5InfraDelta: ["functional-spec.md", "technical-spec.md", "tech-stack.md", "github-context.md", "traceability matrix"],
  phase5DeployPack: ["technical-spec.md", "infra-delta.md", "github-context.md", "test results"],
  phase6Conformance: ["functional-spec.md", "technical-spec.md", "runtime-spec.md", "github-context.md", "verification history"],
  maintenanceTriage: ["maintenance item", "linked story", "functional-spec.md"],
  maintenanceDiagnosis: ["maintenance item", "linked story", "isolated code snippet"],
  maintenanceFixBrief: ["diagnosis.md", "fix-log.md", "linked story"],
  autopilotSetup: ["project-concept.md", "figma-context.md", "guide-the-ai note"],
  autopilotRun: ["locked phase artifacts", "project-concept.md", "functional-spec.md", "technical-spec.md", "runtime-spec.md", "github-context.md"],
} as const;
